apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kcp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kcp
    app.kubernetes.io/part-of: kcp
  name: kcp
  namespace: jduimovich
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kcp
status:
  loadBalancer: {}
